//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMBIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AMBIENTE()
        {
            this.INSTANCIABANCO = new HashSet<INSTANCIABANCO>();
            this.SISTEMAAMBIENTE = new HashSet<SISTEMAAMBIENTE>();
        }
    
        public byte SQAMBIENTE { get; set; }
        public string CDAMBIENTE { get; set; }
        public string DSAMBIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTANCIABANCO> INSTANCIABANCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTEMAAMBIENTE> SISTEMAAMBIENTE { get; set; }
    }
}
