//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMINIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOMINIO()
        {
            this.SISTEMA = new HashSet<SISTEMA>();
        }
    
        public byte SQDOMINIO { get; set; }
        public string CDDOMINIO { get; set; }
        public string NMDOMINIO { get; set; }
        public short NUDIASEXPIRACAOSENHA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTEMA> SISTEMA { get; set; }
    }
}
