//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESQUEMABANCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESQUEMABANCO()
        {
            this.INSTANCIAESQUEMABANCO = new HashSet<INSTANCIAESQUEMABANCO>();
        }
    
        public short SQESQUEMABANCO { get; set; }
        public string CDESQUEMABANCO { get; set; }
        public string DSESQUEMABANCO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTANCIAESQUEMABANCO> INSTANCIAESQUEMABANCO { get; set; }
    }
}
