//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTANCIABANCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTANCIABANCO()
        {
            this.INSTANCIAESQUEMABANCO = new HashSet<INSTANCIAESQUEMABANCO>();
        }
    
        public short SQINSTANCIABANCO { get; set; }
        public string CDINSTANCIABANCO { get; set; }
        public string DSINSTANCIABANCO { get; set; }
        public Nullable<byte> SQAMBIENTE { get; set; }
        public string HOST { get; set; }
        public string PORT { get; set; }
        public string SERVICENAME { get; set; }
    
        public virtual AMBIENTE AMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTANCIAESQUEMABANCO> INSTANCIAESQUEMABANCO { get; set; }
    }
}
