//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGPRIVILEGIO
    {
        public int SQLOGPRIVILEGIO { get; set; }
        public System.DateTime DTLOGPRIVILEGIO { get; set; }
        public string TPACAO { get; set; }
        public string TPPRIVILEGIO { get; set; }
        public string NMOBJETO { get; set; }
        public string NMUSUARIO { get; set; }
        public short SQUSUARIO { get; set; }
        public string DSCOMANDO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
