//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMBIENTE> AMBIENTE { get; set; }
        public virtual DbSet<DOMINIO> DOMINIO { get; set; }
        public virtual DbSet<ESQUEMABANCO> ESQUEMABANCO { get; set; }
        public virtual DbSet<FUNCAO> FUNCAO { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<INSTANCIABANCO> INSTANCIABANCO { get; set; }
        public virtual DbSet<INSTANCIAESQUEMABANCO> INSTANCIAESQUEMABANCO { get; set; }
        public virtual DbSet<LOGERRO> LOGERRO { get; set; }
        public virtual DbSet<LOGPRIVILEGIO> LOGPRIVILEGIO { get; set; }
        public virtual DbSet<MENSAGEM> MENSAGEM { get; set; }
        public virtual DbSet<SISTEMA> SISTEMA { get; set; }
        public virtual DbSet<SISTEMAAMBIENTE> SISTEMAAMBIENTE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIOACESSO> USUARIOACESSO { get; set; }
    }
}
