//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMAAMBIENTE
    {
        public byte SQAMBIENTE { get; set; }
        public short SQSISTEMA { get; set; }
        public string DSURLSISTEMA { get; set; }
    
        public virtual AMBIENTE AMBIENTE { get; set; }
        public virtual SISTEMA SISTEMA { get; set; }
    }
}
