//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SISTEMA()
        {
            this.FUNCAO = new HashSet<FUNCAO>();
            this.GRUPO = new HashSet<GRUPO>();
            this.LOGERRO = new HashSet<LOGERRO>();
            this.SISTEMAAMBIENTE = new HashSet<SISTEMAAMBIENTE>();
            this.USUARIOACESSO = new HashSet<USUARIOACESSO>();
            this.DOMINIO = new HashSet<DOMINIO>();
            this.INSTANCIAESQUEMABANCO = new HashSet<INSTANCIAESQUEMABANCO>();
        }
    
        public short SQSISTEMA { get; set; }
        public string CDSISTEMA { get; set; }
        public string NMSISTEMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCAO> FUNCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO> GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGERRO> LOGERRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTEMAAMBIENTE> SISTEMAAMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOACESSO> USUARIOACESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOMINIO> DOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTANCIAESQUEMABANCO> INSTANCIAESQUEMABANCO { get; set; }
    }
}
