//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOACESSO
    {
        public int SQUSUARIOACESSO { get; set; }
        public System.DateTime DTACESSOSISTEMA { get; set; }
        public string FLUSUARIOLOGADO { get; set; }
        public Nullable<short> SQUSUARIO { get; set; }
        public Nullable<short> SQSISTEMA { get; set; }
        public string DSLOGINREDE { get; set; }
        public string DSMAQUINA { get; set; }
    
        public virtual SISTEMA SISTEMA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
