//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Infra.DbContexto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.LOGPRIVILEGIO = new HashSet<LOGPRIVILEGIO>();
            this.USUARIOACESSO = new HashSet<USUARIOACESSO>();
            this.GRUPO = new HashSet<GRUPO>();
        }
    
        public short SQUSUARIO { get; set; }
        public string CDMATRICULA { get; set; }
        public string NMUSUARIO { get; set; }
        public string DSLOGIN { get; set; }
        public string DSHASHSENHA { get; set; }
        public Nullable<System.DateTime> DTEXPIRACAOSENHA { get; set; }
        public string FLATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGPRIVILEGIO> LOGPRIVILEGIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOACESSO> USUARIOACESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO> GRUPO { get; set; }
    }
}
